name: eimsky_dns_app
description: EIMSKY DNS app for vendor

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.0.0
  get_it: ^7.1.3
  fl_chart: ^0.36.3
  percent_indicator: ^3.0.1
  slide_to_act: ^2.0.1
  flutter_svg: ^0.22.0
  flutter_barcode_scanner: ^2.0.0
  google_maps_flutter: ^2.0.6
  geolocator: ^7.0.3
  geocoding: ^2.0.0
  flutter_spinkit: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/mock/
    - assets/config/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
          weight: 700